### PR TITLE
Add Zitatsuchmaschine with example quote

### PR DESCRIPTION
**Pull request by alanakbik**
I am trying to add a page for Zitatsuchmaschine with an embedded quote as an iFrame. 

However, it is not compiling. Can you let me know what I am doing wrong?

### CODE REVIEW

**Comment by konstantin-lukas** [comment]
There were some issues that arose because the embedding code provided on https://zitatsuchmaschine.informatik.hu-berlin.de/ is just an example using vanilla HTML and this project is using React with JSX syntax.

1. The style attribute of the iframe element has to be an object, not a string
2. The code from Zitatsuchmaschine includes some custom JavaScript which automatically sets the height of the iframe window which you cannot run inside of a script tag. Instead you need to rewrite it the React way.
3. The custom JavaScript from 2. only works on the client so it needs to be extracted into a client-side component.

Note that currently the embedded view of Zitatsuchmaschine includes the footer which looks kind of ugly. This will be removed once branch "hotfix-1497" is merged into dev.

Normally when you include an iframe, you can just copy-paste into a React component. The problem here was the custom styles and the extra JavaScript. If you want to include more quotes from our Zitatsuchmaschine, let me know and I'll modify the iframe component I added to allow loading different quotes.

**Comment by alanakbik** [comment]
Thanks @konstantin-lukas! 

One thing I note is that the light/dark theme is not transferred to the iFrame:
grafik

Aside from this, passing a quote ID would be helpful, but not a priority since I don't think we will have more than one embedded quote.

**Comment by alanakbik** [comment]
Actually, I realized this is because I have the dark theme activated but the page only supports light. Is there a way to force the iframe to always use the light theme?

**Comment by konstantin-lukas** [comment]
The theme inside the iframe is the same as the theme you have selected on zitatsuchmaschine.informatik.hu-berlin.de. For someone who has never visited the site before, they will get the theme that matches their browser. There's currently no way to overwrite this behavior. This is something that would have to be implemented in the Zitatsuchmaschine repo, but this might not be a trivial change.

**Comment by alanakbik** [comment]
@konstantin-lukas ok thanks! The PR is ready for merge now.

**Comment by konstantin-lukas** [comment]
One note: I replaced the images you added with vectorized images. When using logos, please always prefer SVG files over rasterized formats. Also, I added an optional image padding option so that the gallery images don't have to touch their frame.

**Comment by alanakbik** [comment]
Looks great, thanks!

**Pull request merged**
