### PR TITLE
Add more content

### PR DESCRIPTION
**Pull request by alanakbik**
Another test to add some more pictures and persons.

### CODE REVIEW

**Comment by alanakbik** [comment]
update: 
- added more research (stubs only)
- fleshed out the Flair and Fundus research pages

Some things I noted on the Flair page: 
- The HunFlair image speads across the whole screen, which looks strange on desktop
- More whitespace above the H2 headers would be good

**Comment by alanakbik** [comment]
Also, on the research overview page it would be good to make the images clickable so they lead to the respective research page (same functionality as "read more" button)

**Comment by alanakbik** [comment]
Another update: I struggled to find a good way to put an address line by line in the legal note. In the end I used an UL, but it looks a bit weird.

**Comment by konstantin-lukas** [comment]
Some notes:
- You can start a new line with the <br/> element
- Make sure to run the build command before commiting your changes; you had some linting and type errors. Try checking out 219de49 and de54b90 and compare the difference when running `npm run build`

**Pull request merged**
